name: Deploy Cloudflare R2 Bucket

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/**' 
      - '.docker/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/**' 
      - '.docker/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/cloudflare_r2

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.6.0"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_cloudflare_api_token }}
        TF_VAR_cloudflare_account_id: ${{ secrets.TF_VAR_cloudflare_account_id }}
        TF_VAR_cloudflare_bucket_name: ${{ secrets.TF_VAR_cloudflare_bucket_name || 'my-r2-bucket' }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if terraform apply -auto-approve; then
          echo "Bucket created successfully"
        else
          echo "Bucket creation failed - it may already exist"
          echo "To import existing bucket locally:"
          echo "terraform import cloudflare_r2_bucket.cloudflare-bucket ${{ secrets.TF_VAR_cloudflare_account_id }}/${{ secrets.TF_VAR_cloudflare_bucket_name || 'my-r2-bucket' }}"
          exit 1
        fi
      env:
        TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_cloudflare_api_token }}
        TF_VAR_cloudflare_account_id: ${{ secrets.TF_VAR_cloudflare_account_id }}
        TF_VAR_cloudflare_bucket_name: ${{ secrets.TF_VAR_cloudflare_bucket_name || 'my-r2-bucket' }}